version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
      - REPOSITORY_URI=961368246545.dkr.ecr.us-east-2.amazonaws.com/stets
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t stets .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag stets:staging 961368246545.dkr.ecr.us-east-2.amazonaws.com/stets:staging
      - docker push 961368246545.dkr.ecr.us-east-2.amazonaws.com/stets:staging
