version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Showing ENV variables for debug purposes
      - printenv
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t stets .
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker tag stets:latest $REPO_URL:latest
      - docker push $REPO_URL:latest
